// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Command.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace msg {

  /// <summary>Holder for reflection information generated from Command.proto</summary>
  public static partial class CommandReflection {

    #region Descriptor
    /// <summary>File descriptor for Command.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommandReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1Db21tYW5kLnByb3RvEgNtc2cqJgoLQ29tbWFuZFR5cGUSDAoIR0VUVE9L",
            "RU4QABIJCgVMT0dJThABQiUKHWNvbS53ZWl5aS5nYW1lc2VydmVyLnByb3Rv",
            "Y29sqgIDbXNnYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::msg.CommandType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CommandType {
    [pbr::OriginalName("GETTOKEN")] Gettoken = 0,
    [pbr::OriginalName("LOGIN")] Login = 1,
  }

  #endregion

}

#endregion Designer generated code
