// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginBuf.proto

package com.weiyi.gameserver.protocol;

public final class LoginBuf {
  private LoginBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetTokenMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg.GetTokenMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.msg.CommandType cmd = 1;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    int getCmdValue();
    /**
     * <code>.msg.CommandType cmd = 1;</code>
     * @return The cmd.
     */
    com.weiyi.gameserver.protocol.Command.CommandType getCmd();
  }
  /**
   * Protobuf type {@code msg.GetTokenMessage}
   */
  public static final class GetTokenMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg.GetTokenMessage)
      GetTokenMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetTokenMessage.newBuilder() to construct.
    private GetTokenMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetTokenMessage() {
      cmd_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetTokenMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetTokenMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.weiyi.gameserver.protocol.LoginBuf.internal_static_msg_GetTokenMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.weiyi.gameserver.protocol.LoginBuf.internal_static_msg_GetTokenMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage.class, com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>.msg.CommandType cmd = 1;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    @java.lang.Override public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>.msg.CommandType cmd = 1;</code>
     * @return The cmd.
     */
    @java.lang.Override public com.weiyi.gameserver.protocol.Command.CommandType getCmd() {
      @SuppressWarnings("deprecation")
      com.weiyi.gameserver.protocol.Command.CommandType result = com.weiyi.gameserver.protocol.Command.CommandType.valueOf(cmd_);
      return result == null ? com.weiyi.gameserver.protocol.Command.CommandType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != com.weiyi.gameserver.protocol.Command.CommandType.GETTOKEN.getNumber()) {
        output.writeEnum(1, cmd_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != com.weiyi.gameserver.protocol.Command.CommandType.GETTOKEN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage)) {
        return super.equals(obj);
      }
      com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage other = (com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage) obj;

      if (cmd_ != other.cmd_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg.GetTokenMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg.GetTokenMessage)
        com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.weiyi.gameserver.protocol.LoginBuf.internal_static_msg_GetTokenMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.weiyi.gameserver.protocol.LoginBuf.internal_static_msg_GetTokenMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage.class, com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage.Builder.class);
      }

      // Construct using com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.weiyi.gameserver.protocol.LoginBuf.internal_static_msg_GetTokenMessage_descriptor;
      }

      @java.lang.Override
      public com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage getDefaultInstanceForType() {
        return com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage build() {
        com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage buildPartial() {
        com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage result = new com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage(this);
        result.cmd_ = cmd_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage) {
          return mergeFrom((com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage other) {
        if (other == com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage.getDefaultInstance()) return this;
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ = 0;
      /**
       * <code>.msg.CommandType cmd = 1;</code>
       * @return The enum numeric value on the wire for cmd.
       */
      @java.lang.Override public int getCmdValue() {
        return cmd_;
      }
      /**
       * <code>.msg.CommandType cmd = 1;</code>
       * @param value The enum numeric value on the wire for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdValue(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.msg.CommandType cmd = 1;</code>
       * @return The cmd.
       */
      @java.lang.Override
      public com.weiyi.gameserver.protocol.Command.CommandType getCmd() {
        @SuppressWarnings("deprecation")
        com.weiyi.gameserver.protocol.Command.CommandType result = com.weiyi.gameserver.protocol.Command.CommandType.valueOf(cmd_);
        return result == null ? com.weiyi.gameserver.protocol.Command.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>.msg.CommandType cmd = 1;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(com.weiyi.gameserver.protocol.Command.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.msg.CommandType cmd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msg.GetTokenMessage)
    }

    // @@protoc_insertion_point(class_scope:msg.GetTokenMessage)
    private static final com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage();
    }

    public static com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetTokenMessage>
        PARSER = new com.google.protobuf.AbstractParser<GetTokenMessage>() {
      @java.lang.Override
      public GetTokenMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetTokenMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetTokenMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetTokenMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.weiyi.gameserver.protocol.LoginBuf.GetTokenMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msg.LoginMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.msg.CommandType cmd = 1;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    int getCmdValue();
    /**
     * <code>.msg.CommandType cmd = 1;</code>
     * @return The cmd.
     */
    com.weiyi.gameserver.protocol.Command.CommandType getCmd();

    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code msg.LoginMessage}
   */
  public static final class LoginMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msg.LoginMessage)
      LoginMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginMessage.newBuilder() to construct.
    private LoginMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginMessage() {
      cmd_ = 0;
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              cmd_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.weiyi.gameserver.protocol.LoginBuf.internal_static_msg_LoginMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.weiyi.gameserver.protocol.LoginBuf.internal_static_msg_LoginMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.weiyi.gameserver.protocol.LoginBuf.LoginMessage.class, com.weiyi.gameserver.protocol.LoginBuf.LoginMessage.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>.msg.CommandType cmd = 1;</code>
     * @return The enum numeric value on the wire for cmd.
     */
    @java.lang.Override public int getCmdValue() {
      return cmd_;
    }
    /**
     * <code>.msg.CommandType cmd = 1;</code>
     * @return The cmd.
     */
    @java.lang.Override public com.weiyi.gameserver.protocol.Command.CommandType getCmd() {
      @SuppressWarnings("deprecation")
      com.weiyi.gameserver.protocol.Command.CommandType result = com.weiyi.gameserver.protocol.Command.CommandType.valueOf(cmd_);
      return result == null ? com.weiyi.gameserver.protocol.Command.CommandType.UNRECOGNIZED : result;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 2;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 2;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != com.weiyi.gameserver.protocol.Command.CommandType.GETTOKEN.getNumber()) {
        output.writeEnum(1, cmd_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != com.weiyi.gameserver.protocol.Command.CommandType.GETTOKEN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmd_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.weiyi.gameserver.protocol.LoginBuf.LoginMessage)) {
        return super.equals(obj);
      }
      com.weiyi.gameserver.protocol.LoginBuf.LoginMessage other = (com.weiyi.gameserver.protocol.LoginBuf.LoginMessage) obj;

      if (cmd_ != other.cmd_) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + cmd_;
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.weiyi.gameserver.protocol.LoginBuf.LoginMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msg.LoginMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msg.LoginMessage)
        com.weiyi.gameserver.protocol.LoginBuf.LoginMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.weiyi.gameserver.protocol.LoginBuf.internal_static_msg_LoginMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.weiyi.gameserver.protocol.LoginBuf.internal_static_msg_LoginMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.weiyi.gameserver.protocol.LoginBuf.LoginMessage.class, com.weiyi.gameserver.protocol.LoginBuf.LoginMessage.Builder.class);
      }

      // Construct using com.weiyi.gameserver.protocol.LoginBuf.LoginMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        token_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.weiyi.gameserver.protocol.LoginBuf.internal_static_msg_LoginMessage_descriptor;
      }

      @java.lang.Override
      public com.weiyi.gameserver.protocol.LoginBuf.LoginMessage getDefaultInstanceForType() {
        return com.weiyi.gameserver.protocol.LoginBuf.LoginMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.weiyi.gameserver.protocol.LoginBuf.LoginMessage build() {
        com.weiyi.gameserver.protocol.LoginBuf.LoginMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.weiyi.gameserver.protocol.LoginBuf.LoginMessage buildPartial() {
        com.weiyi.gameserver.protocol.LoginBuf.LoginMessage result = new com.weiyi.gameserver.protocol.LoginBuf.LoginMessage(this);
        result.cmd_ = cmd_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.weiyi.gameserver.protocol.LoginBuf.LoginMessage) {
          return mergeFrom((com.weiyi.gameserver.protocol.LoginBuf.LoginMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.weiyi.gameserver.protocol.LoginBuf.LoginMessage other) {
        if (other == com.weiyi.gameserver.protocol.LoginBuf.LoginMessage.getDefaultInstance()) return this;
        if (other.cmd_ != 0) {
          setCmdValue(other.getCmdValue());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.weiyi.gameserver.protocol.LoginBuf.LoginMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.weiyi.gameserver.protocol.LoginBuf.LoginMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ = 0;
      /**
       * <code>.msg.CommandType cmd = 1;</code>
       * @return The enum numeric value on the wire for cmd.
       */
      @java.lang.Override public int getCmdValue() {
        return cmd_;
      }
      /**
       * <code>.msg.CommandType cmd = 1;</code>
       * @param value The enum numeric value on the wire for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdValue(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.msg.CommandType cmd = 1;</code>
       * @return The cmd.
       */
      @java.lang.Override
      public com.weiyi.gameserver.protocol.Command.CommandType getCmd() {
        @SuppressWarnings("deprecation")
        com.weiyi.gameserver.protocol.Command.CommandType result = com.weiyi.gameserver.protocol.Command.CommandType.valueOf(cmd_);
        return result == null ? com.weiyi.gameserver.protocol.Command.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>.msg.CommandType cmd = 1;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(com.weiyi.gameserver.protocol.Command.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cmd_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.msg.CommandType cmd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 2;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msg.LoginMessage)
    }

    // @@protoc_insertion_point(class_scope:msg.LoginMessage)
    private static final com.weiyi.gameserver.protocol.LoginBuf.LoginMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.weiyi.gameserver.protocol.LoginBuf.LoginMessage();
    }

    public static com.weiyi.gameserver.protocol.LoginBuf.LoginMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginMessage>
        PARSER = new com.google.protobuf.AbstractParser<LoginMessage>() {
      @java.lang.Override
      public LoginMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.weiyi.gameserver.protocol.LoginBuf.LoginMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_GetTokenMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_GetTokenMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msg_LoginMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msg_LoginMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016LoginBuf.proto\022\003msg\032\rCommand.proto\"0\n\017" +
      "GetTokenMessage\022\035\n\003cmd\030\001 \001(\0162\020.msg.Comma" +
      "ndType\"<\n\014LoginMessage\022\035\n\003cmd\030\001 \001(\0162\020.ms" +
      "g.CommandType\022\r\n\005token\030\002 \001(\tB%\n\035com.weiy" +
      "i.gameserver.protocol\252\002\003msgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.weiyi.gameserver.protocol.Command.getDescriptor(),
        });
    internal_static_msg_GetTokenMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msg_GetTokenMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_GetTokenMessage_descriptor,
        new java.lang.String[] { "Cmd", });
    internal_static_msg_LoginMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_msg_LoginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msg_LoginMessage_descriptor,
        new java.lang.String[] { "Cmd", "Token", });
    com.weiyi.gameserver.protocol.Command.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
